services:
  cuteoverload:
    build: .
    container_name: cuteoverload
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./data:/app/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cuteoverload.rule=Host(`cuteoverload.tinetov.net`)"
      - "traefik.http.routers.cuteoverload.entrypoints=web"
      - "traefik.http.services.cuteoverload.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true
